alter PROC [dbo].[SP_TEST]
AS
BEGIN
	IF 1=0 BEGIN
		SET FMTONLY OFF
	END

	SELECT LTC.MALTC, SOSVDADANGKY = COUNT(MASV) INTO #DSSOSVDANGKY
	FROM (SELECT MALTC FROM LOPTINCHI WITH (INDEX=IX_NIENKHOA)) LTC
	LEFT JOIN (SELECT MALTC, MASV FROM DANGKY WHERE HUYDANGKY = 'FALSE') DK 
	ON LTC.MALTC = DK.MALTC
	GROUP BY LTC.MALTC

	SELECT LTC.MALTC, NIENKHOA, HOCKY, LTC.MAMH, TENMH, NHOM, LTC.MAGV, HOTENGV = HO + ' ' + TEN, MAKHOA, SOSVTOITHIEU, SOSVDADANGKY, HUYLOP
	FROM (SELECT * FROM LOPTINCHI WITH (INDEX=IX_NIENKHOA)) LTC,
		(SELECT MAMH, TENMH FROM MONHOC) MH, 
		(SELECT MAGV, HO, TEN FROM GIANGVIEN) GV, #DSSOSVDANGKY
	WHERE  LTC.MAMH = MH.MAMH AND LTC.MAGV = GV.MAGV AND LTC.MALTC = #DSSOSVDANGKY.MALTC
END
GO
-- [dbo].[SP_TEST]